# Generated by Django 5.2.4 on 2025-09-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contaminante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NivelICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('rango_min', models.FloatField()),
                ('rango_max', models.FloatField()),
                ('color_seleccionado', models.CharField(choices=[('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Rojo', 'Rojo'), ('Morado', 'Morado'), ('Marrón', 'Marrón')], default='Verde', max_length=20)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('clasificacion_salud', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Muy Malo', 'Muy Malo'), ('Crítico', 'Crítico')], default='Bueno', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fuente', models.CharField(choices=[('OpenAQ', 'OpenAQ'), ('IQAir', 'IQAir'), ('AMDC', 'AMDC')], default='OpenAQ', max_length=20)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.entidad')),
                ('localidad', models.ForeignKey(default='Distrito Central', on_delete=django.db.models.deletion.CASCADE, to='clima_app.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('contaminante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.contaminante')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='NivelesContaminantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.FloatField(default=0)),
                ('limite_superior', models.FloatField(default=0)),
                ('acciones', models.CharField(max_length=200, null=True)),
                ('contaminante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.contaminante')),
                ('nivel_ica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima_app.nivelica')),
            ],
        ),
    ]
