# Generated by Django 5.2.4 on 2025-09-15 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='entidad',
            field=models.ForeignKey(default='Municipalidad del Distrito Central', on_delete=django.db.models.deletion.CASCADE, to='clima_app.entidad'),
        ),
    ]
