# Generated by Django 5.2.4 on 2025-09-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima_app', '0002_alter_estacion_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clima_app.entidad'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clima_app.localidad'),
        ),
    ]
