name: Deploy DB to Render

on:
  workflow_dispatch:

jobs:
  migrate-and-seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      - name: Run migrations
        working-directory: ProyectoClima
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_SETTINGS_MODULE: ProyectoClima.settings
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/ProyectoClima
        run: python manage.py migrate --noinput

      - name: Load initial data
        working-directory: ProyectoClima
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_SETTINGS_MODULE: ProyectoClima.settings
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/ProyectoClima
        run: python manage.py loaddata ../initial_data.json
