name: Run Scraper

on:
  schedule:
    - cron: "0 14 * * *" # 08:00 Honduras (UTC-6)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files (debug root)
        run: ls -R

      - name: Locate scraping.py
        id: locate
        run: |
          set -e
          SCRIPT_PATH="$(find . -type f -name 'scraping.py' | head -n 1)"
          if [ -z "$SCRIPT_PATH" ]; then
            echo "No se encontró scraping.py"; exit 1
          fi
          echo "SCRIPT_PATH=$SCRIPT_PATH" >> $GITHUB_ENV
          echo "Encontrado: $SCRIPT_PATH"

      - name: Show parent folders (debug)
        run: |
          echo "SCRIPT_PATH=$SCRIPT_PATH"
          SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
          echo "SCRIPT_DIR=$SCRIPT_DIR"
          ls -la "$SCRIPT_DIR"
          CANDIDATE_BASE="$(dirname "$(dirname "$SCRIPT_DIR")")"
          echo "CANDIDATE_BASE=$CANDIDATE_BASE"
          ls -la "$CANDIDATE_BASE" || true

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (runner python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      - name: Run scraping script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/ProyectoClima
          DJANGO_SETTINGS_MODULE: ProyectoClima.settings
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          echo "DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"
          python "$SCRIPT_PATH"

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraping_screenshot
          path: scraping_test.png
