name: Run Scraper

on:
  schedule:
    - cron: "0 14 * * *" # todos los días a las 8AM Honduras (14:00 UTC)
  workflow_dispatch: # también ejecutable manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files (debug)
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      - name: Run scraping script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          source .venv/bin/activate
          python clima_app/scripts/scraping.py
